### ISSUE TITLE
running cli commands

### ISSUE THREAD

**Issue by alshamsi97** [lucent-sea/OnvifDotNet#1]
im facing this issue 
"
Unhandled exception: System.TypeInitializationException: The type initializer for 'OnvifDotNet.Core.Helpers.OnvifHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libvlc' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibvlc, 0x0001): tried: 'liblibvlc' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibvlc' (no such file), '/usr/lib/liblibvlc' (no such file, not in dyld cache), 'liblibvlc' (no such file), '/usr/local/lib/liblibvlc' (no such file), '/usr/lib/liblibvlc' (no such file, not in dyld cache)
 "

**Comment by bitbound** [comment]
My apologies.  This repo was only an experiment while I was messing with IP cameras.  It's not being supported or further developed.  I'll archive it so it's clear.
